name: Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: ["ubuntu-latest", "windows-latest", "macos-latest"]
        python-version: ["3.12", "3.11"]

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: setup.py

      # Install DVC
      - name: Install DVC
        run: |
          python -m pip install -U pip setuptools wheel
          pip install dvc[gs]

      # Pull data using DVC
      - name: DVC Pull
        run: |
          dvc pull
        env:
          DVC_NO_ANALYTICS: "true"  # Optional: Disable DVC analytics for privacy

      # Install other dependencies
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip list

      # Run tests and coverage
      - name: Run tests & coverage
        run: |
          coverage run -m pytest tests/
          coverage report -m
